Play travis
Otus-DevOps-2020-11/IvanPrivalov_infra pull request #2
Opened 2021-01-09 18:16 UTC by IvanPrivalov

2021-01-11 07:05 UTC, mrgreyves requested changes
Здравствуйте! Отметил ошибку в файле, так же нужно добавить описание к вашему пр. ДЗ возвращаю на доработку.

2021-01-11 07:05 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Ошибка!)

2021-01-11 17:54 UTC, IvanPrivalov commented
Добрый вечер. Добавил описание ДЗ и исправил ошибку в файле test.py

2021-01-12 06:20 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-01-12 17:05 UTC, merged